//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StringTemplates", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: center;&quot;&gt;&lt;object type=&quot;application/x-shockwave-flash&quot; data=&quot;http://dubaonhanluchcmc.gov.vn/vcastr3.swf&quot; width=&quot;400&quot; height=&quot;300&quot; id=&quot;vcastr3&quot;&gt;
        ///		&lt;param name=&apos;wmode&apos; value=&apos;opaque&apos; /&gt;
        ///		&lt;param name=&apos;movie&apos; value=&apos;http://dubaonhanluchcmc.gov.vn/vcastr3.swf&apos; /&gt;
        ///		&lt;param name=&apos;allowFullScreen&apos; value=&apos;true&apos; /&gt;
        ///		&lt;param name=&apos;FlashVars&apos; value=&apos;xml=&lt;vcastr&gt;&lt;channel&gt;&lt;item&gt;&lt;source&gt;{0}&lt;/source&gt;&lt;duration&gt;&lt;/duration&gt;&lt;title&gt;{1}&lt;/title&gt;&lt;/item&gt;&lt;/channel&gt;&lt;config&gt;&lt;bufferTime&gt;4&lt;/bufferTime&gt;&lt;contralP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VideoPlayer {
            get {
                return ResourceManager.GetString("VideoPlayer", resourceCulture);
            }
        }
    }
}
